### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rdelfin** [pfent/libibverbscpp#5]
Hello! I was considering using this library for a project but I noticed there's not license provided anywhere in the repo. What license is this code given under? Thanks!

**Comment by pfent** [comment]
I intended to follow the same license as the libibverbs from rdma-core and noted this in the README.  The license situation of rdma-core is [a bit confusing](https://github.com/linux-rdma/rdma-core/blob/master/COPYING.md). 

I just pushed an explicit MIT license to this repo, which should hopefully clear up any questions
