### ISSUE TITLE
`IBV_REREG_MR_KEEP_VALID` was not declared in this scope

### ISSUE THREAD

**Issue by shrebhan** [pfent/libibverbscpp#7]
Hello,
I'm trying to run the examples, getting this error - 

```
`In file included from /root/libibverbscpp/librdmacmcpp.h:4,
                 from /root/libibverbscpp/example/rdmacm_client.cpp:36:
/root/libibverbscpp/libibverbscpp.h:819:18: error: 'IBV_REREG_MR_KEEP_VALID' was not declared in this scope
     KEEP_VALID = IBV_REREG_MR_KEEP_VALID,
                  ^~~~~~~~~~~~~~~~~~~~~~~
/root/libibverbscpp/libibverbscpp.h:819:18: note: suggested alternative: 'IBV_REREG_MR_ERR_CMD'
     KEEP_VALID = IBV_REREG_MR_KEEP_VALID,
                  ^~~~~~~~~~~~~~~~~~~~~~~
                  IBV_REREG_MR_ERR_CMD`
```

**Comment by filippoSelvatici** [comment]
Hi, I have the same problem. I added this project as a submodule in my own project and since when I changed the OS from ubuntu 20.04 to 22.04 I started having the error above. I tried compiling with multiple versions of GCC (10.4, 11.3, 12.1) but nothing changes.
Sorry for the vague description, I can try to provide more information if needed.
Thanks in advance.

**Comment by filippoSelvatici** [comment]
After further investigation, I noticed that the rdma-core repo actually removed `IBV_REREG_MR_KEEP_VALID` from the enum with [this](https://github.com/linux-rdma/rdma-core/commit/f734b1a62cfc0c2774d20b531fb0cb98fed458ec#) commit. Therefore **this C++ bindings are not up-to-date with the newest version of the rdma-core**.

In the code we include the verbs header [here](https://github.com/pfent/libibverbscpp/blob/d64079d3eaa9512b5abd8b722fe348a64f23879b/libibverbscpp.h#LL5C30-L5C30), and it does not define `IBV_REREG_MR_KEEP_VALID` so the compilation fails.

**Comment by shrebhan** [comment]
@filippoSelvatici were you able to send large sizes of data like (4kb+) with this library ?
